version: "3.9"

services:
  devopsdb:
    image: devopstej/automation:db
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  application:
    image: devopstej/automation:app
    ports:
      - "1111:8080"
    networks:
      - mynetwork
    deploy:
      replicas: 3

networks:
  mynetwork:
    driver: overlay
